<?php
namespace onegraphics\test\models;

use craft\base\Model;

class Settings extends Model {
    public $testEnabled = true;

    public function rules(): array
    {
        return [
            [['testEnabled'], 'required']
        ]; // TODO: Change the autogenerated stub
    }
}