<?php
namespace onegraphics\test\models;

use craft\base\Model;
use onegraphics\test\Test;

class Settings extends Model {
    public bool $testEnabled = true;

    public function rules(): array
    {
        Test::getInstance()->testService->foo();
        return [
            [['testEnabled'], 'required']
        ]; // TODO: Change the autogenerated stub
    }
}